# Generated by Django 2.2.4 on 2019-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_mainfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfeedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
