# Generated by Django 2.2.4 on 2019-10-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabletBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(upload_to='static/img/tabletbrands/')),
            ],
            options={
                'verbose_name': 'TabletBrand',
                'verbose_name_plural': 'TabletBrands',
            },
        ),
        migrations.CreateModel(
            name='TabletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='static/img/tabletmodels')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablets.TabletBrand')),
            ],
            options={
                'verbose_name': 'TabletModel',
                'verbose_name_plural': 'TabletModels',
            },
        ),
    ]
