# Generated by Django 2.2.4 on 2019-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletmodel',
            name='price1',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price10',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price2',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price3',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price4',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price5',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price6',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price7',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price8',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='price9',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv1',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv10',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv2',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv3',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv4',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv5',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv6',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv7',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv8',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='tabletmodel',
            name='serv9',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
    ]
