# Generated by Django 2.2.4 on 2019-10-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(upload_to='static/img/laptopbrands/')),
            ],
            options={
                'verbose_name': 'LaptopBrand',
                'verbose_name_plural': 'LaptopBrands',
            },
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='static/img/laptopmodels/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.LaptopBrand')),
            ],
            options={
                'verbose_name': 'LaptopModel',
                'verbose_name_plural': 'LaptopModels',
            },
        ),
    ]
