# Generated by Django 2.2.4 on 2019-10-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(upload_to='static/img/phonebrands/')),
            ],
            options={
                'verbose_name': 'PhoneBrand',
                'verbose_name_plural': 'PhoneBrands',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/img/phonemodels/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.PhoneBrand')),
            ],
            options={
                'verbose_name': 'PhoneModel',
                'verbose_name_plural': 'PhoneModels',
            },
        ),
    ]
