# Generated by Django 2.2.4 on 2019-10-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(default='123'),
        ),
    ]
