# Generated by Django 2.2.4 on 2019-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20191013_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='price1',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price10',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price2',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price3',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price4',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price5',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price6',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price7',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price8',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='price9',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv1',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv10',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv2',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv3',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv4',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv5',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv6',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv7',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv8',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='serv9',
            field=models.CharField(default='Замена Дисплея', max_length=50),
        ),
    ]
