# Generated by Django 2.2.4 on 2019-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerabrand',
            options={'verbose_name': 'Бренд Фотоаппаратов', 'verbose_name_plural': 'Бренды Фотоаппаратов'},
        ),
        migrations.AlterModelOptions(
            name='cameramodel',
            options={'verbose_name': 'Модель Фотоаппаратов', 'verbose_name_plural': 'Модели Фотоаппаратов'},
        ),
        migrations.AlterField(
            model_name='camerabrand',
            name='logo',
            field=models.ImageField(upload_to='static/img/camerabrands/', verbose_name='Изображение (формат PNG размер 200x200)'),
        ),
        migrations.AlterField(
            model_name='camerabrand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='camerabrand',
            name='slug',
            field=models.SlugField(verbose_name='Слаг-поле (То же, что и название бренда, только вместо пробела тире)'),
        ),
    ]
