# Generated by Django 2.2.4 on 2019-10-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20191028_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='price1',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price10',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price2',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price3',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price4',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price5',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price6',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price7',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price8',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price9',
            field=models.IntegerField(default=1000),
        ),
    ]
