# Generated by Django 3.0.1 on 2020-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200422_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('sea', 'sea'), ('fruit', 'fruit'), ('beverages', 'beverages'), ('dairy', 'dairy')], default='fruit', max_length=20),
        ),
    ]
