# Generated by Django 2.2.10 on 2020-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('group', models.CharField(choices=[('sea', 'sea'), ('fruit', 'fruit'), ('beverages', 'beverages'), ('dairy', 'dairy')], default='fruit', max_length=20)),
                ('img', models.ImageField(default='noimage.jpg', upload_to='product_image')),
            ],
        ),
    ]
