# Generated by Django 2.2.10 on 2020-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('sea', 'sea'), ('beverages', 'beverages'), ('dairy', 'dairy'), ('fruit', 'fruit')], default='fruit', max_length=20),
        ),
    ]
